#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = "os"
    style = "plain"
    foreground = "white"
    template = "{{ .Icon }} "

      [blocks.segments.properties]
        display_distro_name = false

  [[blocks.segments]]
    type = "shell"
    style = "plain"
    template = "{{ if gt .Name \"zsh\"}}{{ .Name }}{{ end }} "

  [[blocks.segments]]
    type = "session"
    style = "plain"
    foreground = "magenta"
    template = "{{ if .SSHSession }} {{ .UserName }}@{{.HostName}} {{ end }}"

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = '#ff9b00'
    template = '{{ .Path }}'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'python'
    style = 'plain'
    foreground = 'yellow'
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ if .Venv }} ({{ .Venv }}){{ else }}{{ end }}{{ end }}'

      [blocks.segments.properties]
        folder_name_fallback = false
        display_mode = 'context'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'p:grey'
    background = 'transparent'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'

    [blocks.segments.properties]
      branch_icon = ' '
      commit_icon = '@'
      fetch_status = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'yellow'
    background = 'transparent'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 5000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}magenta{{end}}",
    ]
    background = 'transparent'
    template = "╰─❱"


[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}magenta{{end}}",
  ]
  background = 'transparent'
  template = '❱ '

[secondary_prompt]
  foreground = 'magenta'
  background = 'transparent'
  template = '╰─❱❱ '