#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = "shell"
    style = "plain"
    template = "{{ if gt .Name \"zsh\"}}{{ .Name }}{{ end }} "

  [[blocks.segments]]
    type = "session"
    style = "plain"
    foreground = "lightYellow"
    background = "transparent"
    template = "{{ .UserName }}@{{.HostName}} <7>in</>"

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = 'yellow'
    background = 'transparent'
    template = ' {{ .Path }}'

    [blocks.segments.properties]
      style = 'full'
      mapped_locations_enabled = false

  [[blocks.segments]]
    type = 'python'
    style = 'plain'
    foreground = 'lightYellow'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}Python {{ .Full }}{{ if .Venv }} ({{ .Venv }}){{ else }}{{ end }}{{ end }}'

      [blocks.segments.properties]
        folder_name_fallback = false
        display_mode = 'context'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'cyan'
    background = 'transparent'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} {{ if gt .Behind 0 }}{{ .Behind }}«{{ end }}{{ if gt .Ahead 0 }}»{{ .Ahead }}{{ end }}'

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'lightYellow'
    background = 'transparent'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 5000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}magenta{{end}}",
    ]
    background = 'transparent'
    template = "<b>└-></b>"


[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}magenta{{end}}",
  ]
  background = 'transparent'
  template = '<b>> </b>'

[secondary_prompt]
  foreground = 'magenta'
  background = 'transparent'
  template = '<b>└->></b>'

